// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v4.0.0
// source: org/xrpl/rpc/v1/get_transaction.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Next field: 4
type GetTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// hash of the transaction. 32 bytes
	// ATTN: this is in binary, not hex. The JSON API accepts a hex string for
	// a transaction hash, but here we need that hex string converted into its
	// binary form. Each pair of hex characters should be converted into its
	// corresponding byte. For example, the 4 character hex string "00FF"
	// should be converted to a 2 byte array: [0, 255]
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// if true, return data in binary format. defaults to false
	Binary bool `protobuf:"varint,2,opt,name=binary,proto3" json:"binary,omitempty"`
	// If the transaction was not found, server will report whether the entire
	// specified range was searched. The value is contained in the error message.
	// The error message is of the form:
	// "txn not found. searched_all = [true,false]"
	// If the transaction was found, this parameter is ignored.
	LedgerRange *LedgerRange `protobuf:"bytes,3,opt,name=ledger_range,json=ledgerRange,proto3" json:"ledger_range,omitempty"`
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_xrpl_rpc_v1_get_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_get_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_get_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *GetTransactionRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *GetTransactionRequest) GetBinary() bool {
	if x != nil {
		return x.Binary
	}
	return false
}

func (x *GetTransactionRequest) GetLedgerRange() *LedgerRange {
	if x != nil {
		return x.LedgerRange
	}
	return nil
}

// Next field: 9
type GetTransactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to SerializedTransaction:
	//	*GetTransactionResponse_Transaction
	//	*GetTransactionResponse_TransactionBinary
	SerializedTransaction isGetTransactionResponse_SerializedTransaction `protobuf_oneof:"serialized_transaction"`
	// Sequence number of ledger that contains this transaction
	LedgerIndex uint32 `protobuf:"varint,3,opt,name=ledger_index,json=ledgerIndex,proto3" json:"ledger_index,omitempty"`
	// 32 bytes
	Hash []byte `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	// whether the ledger has been validated
	Validated bool `protobuf:"varint,5,opt,name=validated,proto3" json:"validated,omitempty"`
	// metadata about the transaction
	//
	// Types that are assignable to SerializedMeta:
	//	*GetTransactionResponse_Meta
	//	*GetTransactionResponse_MetaBinary
	SerializedMeta isGetTransactionResponse_SerializedMeta `protobuf_oneof:"serialized_meta"`
	Date           *Date                                   `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_xrpl_rpc_v1_get_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_get_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_get_transaction_proto_rawDescGZIP(), []int{1}
}

func (m *GetTransactionResponse) GetSerializedTransaction() isGetTransactionResponse_SerializedTransaction {
	if m != nil {
		return m.SerializedTransaction
	}
	return nil
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x, ok := x.GetSerializedTransaction().(*GetTransactionResponse_Transaction); ok {
		return x.Transaction
	}
	return nil
}

func (x *GetTransactionResponse) GetTransactionBinary() []byte {
	if x, ok := x.GetSerializedTransaction().(*GetTransactionResponse_TransactionBinary); ok {
		return x.TransactionBinary
	}
	return nil
}

func (x *GetTransactionResponse) GetLedgerIndex() uint32 {
	if x != nil {
		return x.LedgerIndex
	}
	return 0
}

func (x *GetTransactionResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *GetTransactionResponse) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

func (m *GetTransactionResponse) GetSerializedMeta() isGetTransactionResponse_SerializedMeta {
	if m != nil {
		return m.SerializedMeta
	}
	return nil
}

func (x *GetTransactionResponse) GetMeta() *Meta {
	if x, ok := x.GetSerializedMeta().(*GetTransactionResponse_Meta); ok {
		return x.Meta
	}
	return nil
}

func (x *GetTransactionResponse) GetMetaBinary() []byte {
	if x, ok := x.GetSerializedMeta().(*GetTransactionResponse_MetaBinary); ok {
		return x.MetaBinary
	}
	return nil
}

func (x *GetTransactionResponse) GetDate() *Date {
	if x != nil {
		return x.Date
	}
	return nil
}

type isGetTransactionResponse_SerializedTransaction interface {
	isGetTransactionResponse_SerializedTransaction()
}

type GetTransactionResponse_Transaction struct {
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof"`
}

type GetTransactionResponse_TransactionBinary struct {
	// Variable length
	TransactionBinary []byte `protobuf:"bytes,2,opt,name=transaction_binary,json=transactionBinary,proto3,oneof"`
}

func (*GetTransactionResponse_Transaction) isGetTransactionResponse_SerializedTransaction() {}

func (*GetTransactionResponse_TransactionBinary) isGetTransactionResponse_SerializedTransaction() {}

type isGetTransactionResponse_SerializedMeta interface {
	isGetTransactionResponse_SerializedMeta()
}

type GetTransactionResponse_Meta struct {
	Meta *Meta `protobuf:"bytes,6,opt,name=meta,proto3,oneof"`
}

type GetTransactionResponse_MetaBinary struct {
	// Variable length
	MetaBinary []byte `protobuf:"bytes,7,opt,name=meta_binary,json=metaBinary,proto3,oneof"`
}

func (*GetTransactionResponse_Meta) isGetTransactionResponse_SerializedMeta() {}

func (*GetTransactionResponse_MetaBinary) isGetTransactionResponse_SerializedMeta() {}

var File_org_xrpl_rpc_v1_get_transaction_proto protoreflect.FileDescriptor

var file_org_xrpl_rpc_v1_get_transaction_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76,
	0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70,
	0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1a, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72,
	0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72,
	0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x21, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63,
	0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x3f, 0x0a, 0x0c, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0b, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x88, 0x03, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x12, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12,
	0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2b, 0x0a,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x48, 0x01, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0b, 0x6d, 0x65,
	0x74, 0x61, 0x5f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x01, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x61, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x29, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61,
	0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x42, 0x18, 0x0a, 0x16, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x11, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64,
	0x5f, 0x6d, 0x65, 0x74, 0x61, 0x42, 0x17, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70,
	0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x02, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_org_xrpl_rpc_v1_get_transaction_proto_rawDescOnce sync.Once
	file_org_xrpl_rpc_v1_get_transaction_proto_rawDescData = file_org_xrpl_rpc_v1_get_transaction_proto_rawDesc
)

func file_org_xrpl_rpc_v1_get_transaction_proto_rawDescGZIP() []byte {
	file_org_xrpl_rpc_v1_get_transaction_proto_rawDescOnce.Do(func() {
		file_org_xrpl_rpc_v1_get_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_xrpl_rpc_v1_get_transaction_proto_rawDescData)
	})
	return file_org_xrpl_rpc_v1_get_transaction_proto_rawDescData
}

var file_org_xrpl_rpc_v1_get_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_xrpl_rpc_v1_get_transaction_proto_goTypes = []interface{}{
	(*GetTransactionRequest)(nil),  // 0: org.xrpl.rpc.v1.GetTransactionRequest
	(*GetTransactionResponse)(nil), // 1: org.xrpl.rpc.v1.GetTransactionResponse
	(*LedgerRange)(nil),            // 2: org.xrpl.rpc.v1.LedgerRange
	(*Transaction)(nil),            // 3: org.xrpl.rpc.v1.Transaction
	(*Meta)(nil),                   // 4: org.xrpl.rpc.v1.Meta
	(*Date)(nil),                   // 5: org.xrpl.rpc.v1.Date
}
var file_org_xrpl_rpc_v1_get_transaction_proto_depIdxs = []int32{
	2, // 0: org.xrpl.rpc.v1.GetTransactionRequest.ledger_range:type_name -> org.xrpl.rpc.v1.LedgerRange
	3, // 1: org.xrpl.rpc.v1.GetTransactionResponse.transaction:type_name -> org.xrpl.rpc.v1.Transaction
	4, // 2: org.xrpl.rpc.v1.GetTransactionResponse.meta:type_name -> org.xrpl.rpc.v1.Meta
	5, // 3: org.xrpl.rpc.v1.GetTransactionResponse.date:type_name -> org.xrpl.rpc.v1.Date
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_org_xrpl_rpc_v1_get_transaction_proto_init() }
func file_org_xrpl_rpc_v1_get_transaction_proto_init() {
	if File_org_xrpl_rpc_v1_get_transaction_proto != nil {
		return
	}
	file_org_xrpl_rpc_v1_meta_proto_init()
	file_org_xrpl_rpc_v1_ledger_proto_init()
	file_org_xrpl_rpc_v1_transaction_proto_init()
	file_org_xrpl_rpc_v1_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_org_xrpl_rpc_v1_get_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_xrpl_rpc_v1_get_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_org_xrpl_rpc_v1_get_transaction_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GetTransactionResponse_Transaction)(nil),
		(*GetTransactionResponse_TransactionBinary)(nil),
		(*GetTransactionResponse_Meta)(nil),
		(*GetTransactionResponse_MetaBinary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_xrpl_rpc_v1_get_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_xrpl_rpc_v1_get_transaction_proto_goTypes,
		DependencyIndexes: file_org_xrpl_rpc_v1_get_transaction_proto_depIdxs,
		MessageInfos:      file_org_xrpl_rpc_v1_get_transaction_proto_msgTypes,
	}.Build()
	File_org_xrpl_rpc_v1_get_transaction_proto = out.File
	file_org_xrpl_rpc_v1_get_transaction_proto_rawDesc = nil
	file_org_xrpl_rpc_v1_get_transaction_proto_goTypes = nil
	file_org_xrpl_rpc_v1_get_transaction_proto_depIdxs = nil
}
