// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v4.0.0
// source: org/xrpl/rpc/v1/get_account_transaction_history.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Next field: 8
type GetAccountTransactionHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *AccountAddress `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// What ledger to include results from. Specifying a not yet validated
	// ledger results in an error. Not specifying a ledger uses the entire
	// range of validated ledgers available to the server.
	// Note, this parameter acts as a filter, and can only reduce the number of
	// results. Specifying a single ledger will return only transactions from
	// that ledger. This includes specifying a ledger with a Shortcut. For
	// example, specifying SHORTCUT_VALIDATED will result in only transactions
	// that were part of the most recently validated ledger being returned.
	// Specifying a range of ledgers results in only transactions that were
	// included in a ledger within the specified range being returned.
	//
	// Types that are assignable to Ledger:
	//	*GetAccountTransactionHistoryRequest_LedgerSpecifier
	//	*GetAccountTransactionHistoryRequest_LedgerRange
	Ledger isGetAccountTransactionHistoryRequest_Ledger `protobuf_oneof:"ledger"`
	// Return results as binary blobs. Defaults to false.
	Binary bool `protobuf:"varint,4,opt,name=binary,proto3" json:"binary,omitempty"`
	// If set to true, returns values indexed by older ledger first.
	// Default to false.
	Forward bool `protobuf:"varint,5,opt,name=forward,proto3" json:"forward,omitempty"`
	// Limit the number of results. Server may choose a lower limit.
	// If this value is 0, the limit is ignored and the number of results
	// returned is determined by the server
	Limit uint32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	// Marker to resume where previous request left off
	// Used for pagination
	Marker *Marker `protobuf:"bytes,7,opt,name=marker,proto3" json:"marker,omitempty"`
}

func (x *GetAccountTransactionHistoryRequest) Reset() {
	*x = GetAccountTransactionHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountTransactionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTransactionHistoryRequest) ProtoMessage() {}

func (x *GetAccountTransactionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTransactionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetAccountTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountTransactionHistoryRequest) GetAccount() *AccountAddress {
	if x != nil {
		return x.Account
	}
	return nil
}

func (m *GetAccountTransactionHistoryRequest) GetLedger() isGetAccountTransactionHistoryRequest_Ledger {
	if m != nil {
		return m.Ledger
	}
	return nil
}

func (x *GetAccountTransactionHistoryRequest) GetLedgerSpecifier() *LedgerSpecifier {
	if x, ok := x.GetLedger().(*GetAccountTransactionHistoryRequest_LedgerSpecifier); ok {
		return x.LedgerSpecifier
	}
	return nil
}

func (x *GetAccountTransactionHistoryRequest) GetLedgerRange() *LedgerRange {
	if x, ok := x.GetLedger().(*GetAccountTransactionHistoryRequest_LedgerRange); ok {
		return x.LedgerRange
	}
	return nil
}

func (x *GetAccountTransactionHistoryRequest) GetBinary() bool {
	if x != nil {
		return x.Binary
	}
	return false
}

func (x *GetAccountTransactionHistoryRequest) GetForward() bool {
	if x != nil {
		return x.Forward
	}
	return false
}

func (x *GetAccountTransactionHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAccountTransactionHistoryRequest) GetMarker() *Marker {
	if x != nil {
		return x.Marker
	}
	return nil
}

type isGetAccountTransactionHistoryRequest_Ledger interface {
	isGetAccountTransactionHistoryRequest_Ledger()
}

type GetAccountTransactionHistoryRequest_LedgerSpecifier struct {
	LedgerSpecifier *LedgerSpecifier `protobuf:"bytes,2,opt,name=ledger_specifier,json=ledgerSpecifier,proto3,oneof"`
}

type GetAccountTransactionHistoryRequest_LedgerRange struct {
	LedgerRange *LedgerRange `protobuf:"bytes,3,opt,name=ledger_range,json=ledgerRange,proto3,oneof"`
}

func (*GetAccountTransactionHistoryRequest_LedgerSpecifier) isGetAccountTransactionHistoryRequest_Ledger() {
}

func (*GetAccountTransactionHistoryRequest_LedgerRange) isGetAccountTransactionHistoryRequest_Ledger() {
}

// Next field: 8
type GetAccountTransactionHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account        *AccountAddress           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	LedgerIndexMin uint32                    `protobuf:"varint,2,opt,name=ledger_index_min,json=ledgerIndexMin,proto3" json:"ledger_index_min,omitempty"`
	LedgerIndexMax uint32                    `protobuf:"varint,3,opt,name=ledger_index_max,json=ledgerIndexMax,proto3" json:"ledger_index_max,omitempty"`
	Limit          uint32                    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Marker         *Marker                   `protobuf:"bytes,5,opt,name=marker,proto3" json:"marker,omitempty"`
	Transactions   []*GetTransactionResponse `protobuf:"bytes,6,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Validated      bool                      `protobuf:"varint,7,opt,name=validated,proto3" json:"validated,omitempty"`
}

func (x *GetAccountTransactionHistoryResponse) Reset() {
	*x = GetAccountTransactionHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountTransactionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTransactionHistoryResponse) ProtoMessage() {}

func (x *GetAccountTransactionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTransactionHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetAccountTransactionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountTransactionHistoryResponse) GetAccount() *AccountAddress {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *GetAccountTransactionHistoryResponse) GetLedgerIndexMin() uint32 {
	if x != nil {
		return x.LedgerIndexMin
	}
	return 0
}

func (x *GetAccountTransactionHistoryResponse) GetLedgerIndexMax() uint32 {
	if x != nil {
		return x.LedgerIndexMax
	}
	return 0
}

func (x *GetAccountTransactionHistoryResponse) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAccountTransactionHistoryResponse) GetMarker() *Marker {
	if x != nil {
		return x.Marker
	}
	return nil
}

func (x *GetAccountTransactionHistoryResponse) GetTransactions() []*GetTransactionResponse {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetAccountTransactionHistoryResponse) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

// Next field: 3
type Marker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LedgerIndex     uint32 `protobuf:"varint,1,opt,name=ledger_index,json=ledgerIndex,proto3" json:"ledger_index,omitempty"`
	AccountSequence uint32 `protobuf:"varint,2,opt,name=account_sequence,json=accountSequence,proto3" json:"account_sequence,omitempty"`
}

func (x *Marker) Reset() {
	*x = Marker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Marker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Marker) ProtoMessage() {}

func (x *Marker) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Marker.ProtoReflect.Descriptor instead.
func (*Marker) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDescGZIP(), []int{2}
}

func (x *Marker) GetLedgerIndex() uint32 {
	if x != nil {
		return x.LedgerIndex
	}
	return 0
}

func (x *Marker) GetAccountSequence() uint32 {
	if x != nil {
		return x.AccountSequence
	}
	return 0
}

var File_org_xrpl_rpc_v1_get_account_transaction_history_proto protoreflect.FileDescriptor

var file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDesc = []byte{
	0x0a, 0x35, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76,
	0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70,
	0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x25, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72,
	0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1d, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf5, 0x02, 0x0a,
	0x23, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x4d, 0x0a, 0x10, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x72, 0x67, 0x2e,
	0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0f, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x41,
	0x0a, 0x0c, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x72, 0x67, 0x2e,
	0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x22, 0xe7, 0x02, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d,
	0x69, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d, 0x61, 0x78, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x72, 0x12, 0x4b, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x72, 0x67, 0x2e,
	0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x56,
	0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x29, 0x0a, 0x10, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x17, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72,
	0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x02, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDescOnce sync.Once
	file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDescData = file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDesc
)

func file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDescGZIP() []byte {
	file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDescOnce.Do(func() {
		file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDescData)
	})
	return file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDescData
}

var file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_org_xrpl_rpc_v1_get_account_transaction_history_proto_goTypes = []interface{}{
	(*GetAccountTransactionHistoryRequest)(nil),  // 0: org.xrpl.rpc.v1.GetAccountTransactionHistoryRequest
	(*GetAccountTransactionHistoryResponse)(nil), // 1: org.xrpl.rpc.v1.GetAccountTransactionHistoryResponse
	(*Marker)(nil),                 // 2: org.xrpl.rpc.v1.Marker
	(*AccountAddress)(nil),         // 3: org.xrpl.rpc.v1.AccountAddress
	(*LedgerSpecifier)(nil),        // 4: org.xrpl.rpc.v1.LedgerSpecifier
	(*LedgerRange)(nil),            // 5: org.xrpl.rpc.v1.LedgerRange
	(*GetTransactionResponse)(nil), // 6: org.xrpl.rpc.v1.GetTransactionResponse
}
var file_org_xrpl_rpc_v1_get_account_transaction_history_proto_depIdxs = []int32{
	3, // 0: org.xrpl.rpc.v1.GetAccountTransactionHistoryRequest.account:type_name -> org.xrpl.rpc.v1.AccountAddress
	4, // 1: org.xrpl.rpc.v1.GetAccountTransactionHistoryRequest.ledger_specifier:type_name -> org.xrpl.rpc.v1.LedgerSpecifier
	5, // 2: org.xrpl.rpc.v1.GetAccountTransactionHistoryRequest.ledger_range:type_name -> org.xrpl.rpc.v1.LedgerRange
	2, // 3: org.xrpl.rpc.v1.GetAccountTransactionHistoryRequest.marker:type_name -> org.xrpl.rpc.v1.Marker
	3, // 4: org.xrpl.rpc.v1.GetAccountTransactionHistoryResponse.account:type_name -> org.xrpl.rpc.v1.AccountAddress
	2, // 5: org.xrpl.rpc.v1.GetAccountTransactionHistoryResponse.marker:type_name -> org.xrpl.rpc.v1.Marker
	6, // 6: org.xrpl.rpc.v1.GetAccountTransactionHistoryResponse.transactions:type_name -> org.xrpl.rpc.v1.GetTransactionResponse
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_org_xrpl_rpc_v1_get_account_transaction_history_proto_init() }
func file_org_xrpl_rpc_v1_get_account_transaction_history_proto_init() {
	if File_org_xrpl_rpc_v1_get_account_transaction_history_proto != nil {
		return
	}
	file_org_xrpl_rpc_v1_get_transaction_proto_init()
	file_org_xrpl_rpc_v1_account_proto_init()
	file_org_xrpl_rpc_v1_ledger_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountTransactionHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountTransactionHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Marker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GetAccountTransactionHistoryRequest_LedgerSpecifier)(nil),
		(*GetAccountTransactionHistoryRequest_LedgerRange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_xrpl_rpc_v1_get_account_transaction_history_proto_goTypes,
		DependencyIndexes: file_org_xrpl_rpc_v1_get_account_transaction_history_proto_depIdxs,
		MessageInfos:      file_org_xrpl_rpc_v1_get_account_transaction_history_proto_msgTypes,
	}.Build()
	File_org_xrpl_rpc_v1_get_account_transaction_history_proto = out.File
	file_org_xrpl_rpc_v1_get_account_transaction_history_proto_rawDesc = nil
	file_org_xrpl_rpc_v1_get_account_transaction_history_proto_goTypes = nil
	file_org_xrpl_rpc_v1_get_account_transaction_history_proto_depIdxs = nil
}
