// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v4.0.0
// source: org/xrpl/rpc/v1/submit.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// A request to submit the signed transaction to the ledger.
// Next field: 3
type SubmitTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The signed transaction to submit.
	SignedTransaction []byte `protobuf:"bytes,1,opt,name=signed_transaction,json=signedTransaction,proto3" json:"signed_transaction,omitempty"`
	FailHard          bool   `protobuf:"varint,2,opt,name=fail_hard,json=failHard,proto3" json:"fail_hard,omitempty"`
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_xrpl_rpc_v1_submit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_submit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_submit_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTransactionRequest) GetSignedTransaction() []byte {
	if x != nil {
		return x.SignedTransaction
	}
	return nil
}

func (x *SubmitTransactionRequest) GetFailHard() bool {
	if x != nil {
		return x.FailHard
	}
	return false
}

// A response when a signed transaction is submitted to the ledger.
// Next field: 5
type SubmitTransactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Code indicating the preliminary result of the transaction.
	EngineResult *TransactionResult `protobuf:"bytes,1,opt,name=engine_result,json=engineResult,proto3" json:"engine_result,omitempty"`
	// Numeric code indicating the preliminary result of the transaction,
	// directly correlated to engine_result.
	EngineResultCode int64 `protobuf:"varint,2,opt,name=engine_result_code,json=engineResultCode,proto3" json:"engine_result_code,omitempty"`
	// Human-readable explanation of the transaction's preliminary result.
	EngineResultMessage string `protobuf:"bytes,3,opt,name=engine_result_message,json=engineResultMessage,proto3" json:"engine_result_message,omitempty"`
	// 32 bytes
	Hash []byte `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_xrpl_rpc_v1_submit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_submit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_submit_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTransactionResponse) GetEngineResult() *TransactionResult {
	if x != nil {
		return x.EngineResult
	}
	return nil
}

func (x *SubmitTransactionResponse) GetEngineResultCode() int64 {
	if x != nil {
		return x.EngineResultCode
	}
	return 0
}

func (x *SubmitTransactionResponse) GetEngineResultMessage() string {
	if x != nil {
		return x.EngineResultMessage
	}
	return ""
}

func (x *SubmitTransactionResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_org_xrpl_rpc_v1_submit_proto protoreflect.FileDescriptor

var file_org_xrpl_rpc_v1_submit_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x1a,
	0x1a, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x18, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x11, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x68,
	0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x48,
	0x61, 0x72, 0x64, 0x22, 0xda, 0x01, 0x0a, 0x19, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x47, 0x0a, 0x0d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78,
	0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0c, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x42, 0x17, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x02, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_org_xrpl_rpc_v1_submit_proto_rawDescOnce sync.Once
	file_org_xrpl_rpc_v1_submit_proto_rawDescData = file_org_xrpl_rpc_v1_submit_proto_rawDesc
)

func file_org_xrpl_rpc_v1_submit_proto_rawDescGZIP() []byte {
	file_org_xrpl_rpc_v1_submit_proto_rawDescOnce.Do(func() {
		file_org_xrpl_rpc_v1_submit_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_xrpl_rpc_v1_submit_proto_rawDescData)
	})
	return file_org_xrpl_rpc_v1_submit_proto_rawDescData
}

var file_org_xrpl_rpc_v1_submit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_xrpl_rpc_v1_submit_proto_goTypes = []interface{}{
	(*SubmitTransactionRequest)(nil),  // 0: org.xrpl.rpc.v1.SubmitTransactionRequest
	(*SubmitTransactionResponse)(nil), // 1: org.xrpl.rpc.v1.SubmitTransactionResponse
	(*TransactionResult)(nil),         // 2: org.xrpl.rpc.v1.TransactionResult
}
var file_org_xrpl_rpc_v1_submit_proto_depIdxs = []int32{
	2, // 0: org.xrpl.rpc.v1.SubmitTransactionResponse.engine_result:type_name -> org.xrpl.rpc.v1.TransactionResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_org_xrpl_rpc_v1_submit_proto_init() }
func file_org_xrpl_rpc_v1_submit_proto_init() {
	if File_org_xrpl_rpc_v1_submit_proto != nil {
		return
	}
	file_org_xrpl_rpc_v1_meta_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_org_xrpl_rpc_v1_submit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_xrpl_rpc_v1_submit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitTransactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_xrpl_rpc_v1_submit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_xrpl_rpc_v1_submit_proto_goTypes,
		DependencyIndexes: file_org_xrpl_rpc_v1_submit_proto_depIdxs,
		MessageInfos:      file_org_xrpl_rpc_v1_submit_proto_msgTypes,
	}.Build()
	File_org_xrpl_rpc_v1_submit_proto = out.File
	file_org_xrpl_rpc_v1_submit_proto_rawDesc = nil
	file_org_xrpl_rpc_v1_submit_proto_goTypes = nil
	file_org_xrpl_rpc_v1_submit_proto_depIdxs = nil
}
