// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v4.0.0
// source: org/xrpl/rpc/v1/xrp_ledger.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_org_xrpl_rpc_v1_xrp_ledger_proto protoreflect.FileDescriptor

var file_org_xrpl_rpc_v1_xrp_ledger_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76,
	0x31, 0x2f, 0x78, 0x72, 0x70, 0x5f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x31, 0x1a, 0x26, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70,
	0x63, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x6f, 0x72, 0x67,
	0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74,
	0x5f, 0x66, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x6f, 0x72, 0x67, 0x2f,
	0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72,
	0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x35, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xa0, 0x04, 0x0a, 0x13, 0x58, 0x52, 0x50, 0x4c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x26, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78,
	0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x49, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x12, 0x1e, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x11,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x29, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x8b, 0x01, 0x0a, 0x1c,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x34, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x35, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x17, 0x0a, 0x0f, 0x6f, 0x72, 0x67,
	0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x02,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_org_xrpl_rpc_v1_xrp_ledger_proto_goTypes = []interface{}{
	(*GetAccountInfoRequest)(nil),                // 0: org.xrpl.rpc.v1.GetAccountInfoRequest
	(*GetFeeRequest)(nil),                        // 1: org.xrpl.rpc.v1.GetFeeRequest
	(*SubmitTransactionRequest)(nil),             // 2: org.xrpl.rpc.v1.SubmitTransactionRequest
	(*GetTransactionRequest)(nil),                // 3: org.xrpl.rpc.v1.GetTransactionRequest
	(*GetAccountTransactionHistoryRequest)(nil),  // 4: org.xrpl.rpc.v1.GetAccountTransactionHistoryRequest
	(*GetAccountInfoResponse)(nil),               // 5: org.xrpl.rpc.v1.GetAccountInfoResponse
	(*GetFeeResponse)(nil),                       // 6: org.xrpl.rpc.v1.GetFeeResponse
	(*SubmitTransactionResponse)(nil),            // 7: org.xrpl.rpc.v1.SubmitTransactionResponse
	(*GetTransactionResponse)(nil),               // 8: org.xrpl.rpc.v1.GetTransactionResponse
	(*GetAccountTransactionHistoryResponse)(nil), // 9: org.xrpl.rpc.v1.GetAccountTransactionHistoryResponse
}
var file_org_xrpl_rpc_v1_xrp_ledger_proto_depIdxs = []int32{
	0, // 0: org.xrpl.rpc.v1.XRPLedgerAPIService.GetAccountInfo:input_type -> org.xrpl.rpc.v1.GetAccountInfoRequest
	1, // 1: org.xrpl.rpc.v1.XRPLedgerAPIService.GetFee:input_type -> org.xrpl.rpc.v1.GetFeeRequest
	2, // 2: org.xrpl.rpc.v1.XRPLedgerAPIService.SubmitTransaction:input_type -> org.xrpl.rpc.v1.SubmitTransactionRequest
	3, // 3: org.xrpl.rpc.v1.XRPLedgerAPIService.GetTransaction:input_type -> org.xrpl.rpc.v1.GetTransactionRequest
	4, // 4: org.xrpl.rpc.v1.XRPLedgerAPIService.GetAccountTransactionHistory:input_type -> org.xrpl.rpc.v1.GetAccountTransactionHistoryRequest
	5, // 5: org.xrpl.rpc.v1.XRPLedgerAPIService.GetAccountInfo:output_type -> org.xrpl.rpc.v1.GetAccountInfoResponse
	6, // 6: org.xrpl.rpc.v1.XRPLedgerAPIService.GetFee:output_type -> org.xrpl.rpc.v1.GetFeeResponse
	7, // 7: org.xrpl.rpc.v1.XRPLedgerAPIService.SubmitTransaction:output_type -> org.xrpl.rpc.v1.SubmitTransactionResponse
	8, // 8: org.xrpl.rpc.v1.XRPLedgerAPIService.GetTransaction:output_type -> org.xrpl.rpc.v1.GetTransactionResponse
	9, // 9: org.xrpl.rpc.v1.XRPLedgerAPIService.GetAccountTransactionHistory:output_type -> org.xrpl.rpc.v1.GetAccountTransactionHistoryResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_org_xrpl_rpc_v1_xrp_ledger_proto_init() }
func file_org_xrpl_rpc_v1_xrp_ledger_proto_init() {
	if File_org_xrpl_rpc_v1_xrp_ledger_proto != nil {
		return
	}
	file_org_xrpl_rpc_v1_get_account_info_proto_init()
	file_org_xrpl_rpc_v1_get_fee_proto_init()
	file_org_xrpl_rpc_v1_submit_proto_init()
	file_org_xrpl_rpc_v1_get_transaction_proto_init()
	file_org_xrpl_rpc_v1_get_account_transaction_history_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_xrpl_rpc_v1_xrp_ledger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_xrpl_rpc_v1_xrp_ledger_proto_goTypes,
		DependencyIndexes: file_org_xrpl_rpc_v1_xrp_ledger_proto_depIdxs,
	}.Build()
	File_org_xrpl_rpc_v1_xrp_ledger_proto = out.File
	file_org_xrpl_rpc_v1_xrp_ledger_proto_rawDesc = nil
	file_org_xrpl_rpc_v1_xrp_ledger_proto_goTypes = nil
	file_org_xrpl_rpc_v1_xrp_ledger_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// XRPLedgerAPIServiceClient is the client API for XRPLedgerAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type XRPLedgerAPIServiceClient interface {
	// Get account info for an account on the XRP Ledger.
	GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*GetAccountInfoResponse, error)
	// Get the fee for a transaction on the XRP Ledger.
	GetFee(ctx context.Context, in *GetFeeRequest, opts ...grpc.CallOption) (*GetFeeResponse, error)
	// Submit a signed transaction to the XRP Ledger.
	SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error)
	// Get the status of a transaction
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	// Get all validated transactions associated with a given account
	GetAccountTransactionHistory(ctx context.Context, in *GetAccountTransactionHistoryRequest, opts ...grpc.CallOption) (*GetAccountTransactionHistoryResponse, error)
}

type xRPLedgerAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXRPLedgerAPIServiceClient(cc grpc.ClientConnInterface) XRPLedgerAPIServiceClient {
	return &xRPLedgerAPIServiceClient{cc}
}

func (c *xRPLedgerAPIServiceClient) GetAccountInfo(ctx context.Context, in *GetAccountInfoRequest, opts ...grpc.CallOption) (*GetAccountInfoResponse, error) {
	out := new(GetAccountInfoResponse)
	err := c.cc.Invoke(ctx, "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetAccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xRPLedgerAPIServiceClient) GetFee(ctx context.Context, in *GetFeeRequest, opts ...grpc.CallOption) (*GetFeeResponse, error) {
	out := new(GetFeeResponse)
	err := c.cc.Invoke(ctx, "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xRPLedgerAPIServiceClient) SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error) {
	out := new(SubmitTransactionResponse)
	err := c.cc.Invoke(ctx, "/org.xrpl.rpc.v1.XRPLedgerAPIService/SubmitTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xRPLedgerAPIServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xRPLedgerAPIServiceClient) GetAccountTransactionHistory(ctx context.Context, in *GetAccountTransactionHistoryRequest, opts ...grpc.CallOption) (*GetAccountTransactionHistoryResponse, error) {
	out := new(GetAccountTransactionHistoryResponse)
	err := c.cc.Invoke(ctx, "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetAccountTransactionHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XRPLedgerAPIServiceServer is the server API for XRPLedgerAPIService service.
type XRPLedgerAPIServiceServer interface {
	// Get account info for an account on the XRP Ledger.
	GetAccountInfo(context.Context, *GetAccountInfoRequest) (*GetAccountInfoResponse, error)
	// Get the fee for a transaction on the XRP Ledger.
	GetFee(context.Context, *GetFeeRequest) (*GetFeeResponse, error)
	// Submit a signed transaction to the XRP Ledger.
	SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error)
	// Get the status of a transaction
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	// Get all validated transactions associated with a given account
	GetAccountTransactionHistory(context.Context, *GetAccountTransactionHistoryRequest) (*GetAccountTransactionHistoryResponse, error)
}

// UnimplementedXRPLedgerAPIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedXRPLedgerAPIServiceServer struct {
}

func (*UnimplementedXRPLedgerAPIServiceServer) GetAccountInfo(context.Context, *GetAccountInfoRequest) (*GetAccountInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountInfo not implemented")
}
func (*UnimplementedXRPLedgerAPIServiceServer) GetFee(context.Context, *GetFeeRequest) (*GetFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFee not implemented")
}
func (*UnimplementedXRPLedgerAPIServiceServer) SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (*UnimplementedXRPLedgerAPIServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (*UnimplementedXRPLedgerAPIServiceServer) GetAccountTransactionHistory(context.Context, *GetAccountTransactionHistoryRequest) (*GetAccountTransactionHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountTransactionHistory not implemented")
}

func RegisterXRPLedgerAPIServiceServer(s *grpc.Server, srv XRPLedgerAPIServiceServer) {
	s.RegisterService(&_XRPLedgerAPIService_serviceDesc, srv)
}

func _XRPLedgerAPIService_GetAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XRPLedgerAPIServiceServer).GetAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XRPLedgerAPIServiceServer).GetAccountInfo(ctx, req.(*GetAccountInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XRPLedgerAPIService_GetFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XRPLedgerAPIServiceServer).GetFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XRPLedgerAPIServiceServer).GetFee(ctx, req.(*GetFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XRPLedgerAPIService_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XRPLedgerAPIServiceServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.xrpl.rpc.v1.XRPLedgerAPIService/SubmitTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XRPLedgerAPIServiceServer).SubmitTransaction(ctx, req.(*SubmitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XRPLedgerAPIService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XRPLedgerAPIServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XRPLedgerAPIServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XRPLedgerAPIService_GetAccountTransactionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountTransactionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XRPLedgerAPIServiceServer).GetAccountTransactionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetAccountTransactionHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XRPLedgerAPIServiceServer).GetAccountTransactionHistory(ctx, req.(*GetAccountTransactionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _XRPLedgerAPIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "org.xrpl.rpc.v1.XRPLedgerAPIService",
	HandlerType: (*XRPLedgerAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccountInfo",
			Handler:    _XRPLedgerAPIService_GetAccountInfo_Handler,
		},
		{
			MethodName: "GetFee",
			Handler:    _XRPLedgerAPIService_GetFee_Handler,
		},
		{
			MethodName: "SubmitTransaction",
			Handler:    _XRPLedgerAPIService_SubmitTransaction_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _XRPLedgerAPIService_GetTransaction_Handler,
		},
		{
			MethodName: "GetAccountTransactionHistory",
			Handler:    _XRPLedgerAPIService_GetAccountTransactionHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "org/xrpl/rpc/v1/xrp_ledger.proto",
}
