// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v4.0.0
// source: org/xrpl/rpc/v1/amount.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Next field: 3
type CurrencyAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Amount:
	//	*CurrencyAmount_XrpAmount
	//	*CurrencyAmount_IssuedCurrencyAmount
	Amount isCurrencyAmount_Amount `protobuf_oneof:"amount"`
}

func (x *CurrencyAmount) Reset() {
	*x = CurrencyAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_xrpl_rpc_v1_amount_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyAmount) ProtoMessage() {}

func (x *CurrencyAmount) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_amount_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyAmount.ProtoReflect.Descriptor instead.
func (*CurrencyAmount) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_amount_proto_rawDescGZIP(), []int{0}
}

func (m *CurrencyAmount) GetAmount() isCurrencyAmount_Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (x *CurrencyAmount) GetXrpAmount() *XRPDropsAmount {
	if x, ok := x.GetAmount().(*CurrencyAmount_XrpAmount); ok {
		return x.XrpAmount
	}
	return nil
}

func (x *CurrencyAmount) GetIssuedCurrencyAmount() *IssuedCurrencyAmount {
	if x, ok := x.GetAmount().(*CurrencyAmount_IssuedCurrencyAmount); ok {
		return x.IssuedCurrencyAmount
	}
	return nil
}

type isCurrencyAmount_Amount interface {
	isCurrencyAmount_Amount()
}

type CurrencyAmount_XrpAmount struct {
	XrpAmount *XRPDropsAmount `protobuf:"bytes,1,opt,name=xrp_amount,json=xrpAmount,proto3,oneof"`
}

type CurrencyAmount_IssuedCurrencyAmount struct {
	IssuedCurrencyAmount *IssuedCurrencyAmount `protobuf:"bytes,2,opt,name=issued_currency_amount,json=issuedCurrencyAmount,proto3,oneof"`
}

func (*CurrencyAmount_XrpAmount) isCurrencyAmount_Amount() {}

func (*CurrencyAmount_IssuedCurrencyAmount) isCurrencyAmount_Amount() {}

// A representation of an amount of XRP.
// Next field: 2
type XRPDropsAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Drops uint64 `protobuf:"varint,1,opt,name=drops,proto3" json:"drops,omitempty"`
}

func (x *XRPDropsAmount) Reset() {
	*x = XRPDropsAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_xrpl_rpc_v1_amount_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XRPDropsAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XRPDropsAmount) ProtoMessage() {}

func (x *XRPDropsAmount) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_amount_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XRPDropsAmount.ProtoReflect.Descriptor instead.
func (*XRPDropsAmount) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_amount_proto_rawDescGZIP(), []int{1}
}

func (x *XRPDropsAmount) GetDrops() uint64 {
	if x != nil {
		return x.Drops
	}
	return 0
}

// A representation of an amount of issued currency.
// Next field: 4
type IssuedCurrencyAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The currency used to value the amount.
	Currency *Currency `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	// The value of the amount. 8 bytes
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Unique account address of the entity issuing the currency.
	Issuer *AccountAddress `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
}

func (x *IssuedCurrencyAmount) Reset() {
	*x = IssuedCurrencyAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_xrpl_rpc_v1_amount_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssuedCurrencyAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuedCurrencyAmount) ProtoMessage() {}

func (x *IssuedCurrencyAmount) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_amount_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuedCurrencyAmount.ProtoReflect.Descriptor instead.
func (*IssuedCurrencyAmount) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_amount_proto_rawDescGZIP(), []int{2}
}

func (x *IssuedCurrencyAmount) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *IssuedCurrencyAmount) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *IssuedCurrencyAmount) GetIssuer() *AccountAddress {
	if x != nil {
		return x.Issuer
	}
	return nil
}

// Next field: 3
type Currency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 3 character ASCII code
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 160 bit currency code. 20 bytes
	Code []byte `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Currency) Reset() {
	*x = Currency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_xrpl_rpc_v1_amount_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_amount_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_amount_proto_rawDescGZIP(), []int{3}
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

var File_org_xrpl_rpc_v1_amount_proto protoreflect.FileDescriptor

var file_org_xrpl_rpc_v1_amount_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x1a,
	0x1d, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb,
	0x01, 0x0a, 0x0e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x40, 0x0a, 0x0a, 0x78, 0x72, 0x70, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x58, 0x52, 0x50, 0x44, 0x72, 0x6f, 0x70, 0x73,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x78, 0x72, 0x70, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x5d, 0x0a, 0x16, 0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x5f, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x64, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x14, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x0e,
	0x58, 0x52, 0x50, 0x44, 0x72, 0x6f, 0x70, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18,
	0x0a, 0x05, 0x64, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30,
	0x01, 0x52, 0x05, 0x64, 0x72, 0x6f, 0x70, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x14, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x35, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x37,
	0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x31, 0x0a, 0x0f, 0x6f,
	0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x50, 0x01,
	0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x78, 0x78,
	0x79, 0x75, 0x6e, 0x2f, 0x72, 0x69, 0x70, 0x70, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_org_xrpl_rpc_v1_amount_proto_rawDescOnce sync.Once
	file_org_xrpl_rpc_v1_amount_proto_rawDescData = file_org_xrpl_rpc_v1_amount_proto_rawDesc
)

func file_org_xrpl_rpc_v1_amount_proto_rawDescGZIP() []byte {
	file_org_xrpl_rpc_v1_amount_proto_rawDescOnce.Do(func() {
		file_org_xrpl_rpc_v1_amount_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_xrpl_rpc_v1_amount_proto_rawDescData)
	})
	return file_org_xrpl_rpc_v1_amount_proto_rawDescData
}

var file_org_xrpl_rpc_v1_amount_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_org_xrpl_rpc_v1_amount_proto_goTypes = []interface{}{
	(*CurrencyAmount)(nil),       // 0: org.xrpl.rpc.v1.CurrencyAmount
	(*XRPDropsAmount)(nil),       // 1: org.xrpl.rpc.v1.XRPDropsAmount
	(*IssuedCurrencyAmount)(nil), // 2: org.xrpl.rpc.v1.IssuedCurrencyAmount
	(*Currency)(nil),             // 3: org.xrpl.rpc.v1.Currency
	(*AccountAddress)(nil),       // 4: org.xrpl.rpc.v1.AccountAddress
}
var file_org_xrpl_rpc_v1_amount_proto_depIdxs = []int32{
	1, // 0: org.xrpl.rpc.v1.CurrencyAmount.xrp_amount:type_name -> org.xrpl.rpc.v1.XRPDropsAmount
	2, // 1: org.xrpl.rpc.v1.CurrencyAmount.issued_currency_amount:type_name -> org.xrpl.rpc.v1.IssuedCurrencyAmount
	3, // 2: org.xrpl.rpc.v1.IssuedCurrencyAmount.currency:type_name -> org.xrpl.rpc.v1.Currency
	4, // 3: org.xrpl.rpc.v1.IssuedCurrencyAmount.issuer:type_name -> org.xrpl.rpc.v1.AccountAddress
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_org_xrpl_rpc_v1_amount_proto_init() }
func file_org_xrpl_rpc_v1_amount_proto_init() {
	if File_org_xrpl_rpc_v1_amount_proto != nil {
		return
	}
	file_org_xrpl_rpc_v1_account_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_org_xrpl_rpc_v1_amount_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_xrpl_rpc_v1_amount_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XRPDropsAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_xrpl_rpc_v1_amount_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssuedCurrencyAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_xrpl_rpc_v1_amount_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Currency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_org_xrpl_rpc_v1_amount_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*CurrencyAmount_XrpAmount)(nil),
		(*CurrencyAmount_IssuedCurrencyAmount)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_xrpl_rpc_v1_amount_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_xrpl_rpc_v1_amount_proto_goTypes,
		DependencyIndexes: file_org_xrpl_rpc_v1_amount_proto_depIdxs,
		MessageInfos:      file_org_xrpl_rpc_v1_amount_proto_msgTypes,
	}.Build()
	File_org_xrpl_rpc_v1_amount_proto = out.File
	file_org_xrpl_rpc_v1_amount_proto_rawDesc = nil
	file_org_xrpl_rpc_v1_amount_proto_goTypes = nil
	file_org_xrpl_rpc_v1_amount_proto_depIdxs = nil
}
